name: WorkflowPro CI

on:
  push:
    branches:
      - master
      - main

jobs:

  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: WorkFlowProNew.API

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Publish API
        run: dotnet publish -c Release -o publish

  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: WorkFlowProNew.UI

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build React
        run: npm run build